stages:
  - build
  - deploy

build:
  image: node:14.16.0
  stage: build
  script:
    - echo "$BUILD_ENV_STAGING" > .env.production
    - cat .env.production
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 day
    paths:
      - dist
  only:
    - staging
    - production

deploy_staging:
  image: alpine
  stage: deploy
  script:
    - "which ssh-agent || ( apk update && apk add openssh-client )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_STAGING" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - apk add rsync
    - rsync -rav --delete dist/ $CI_HOST_STAGING:$CI_FOLDER_STAGING
  only:
    - staging
